### ISSUE TITLE
Documention is severly lacking

### ISSUE THREAD

**Issue by natschil** [CoherentStructures/OceanTools.jl#1]
Title is self-explanatory. There isn't even an example of how to use the package, it seems like the whole thing is a mess of undocumented code, is anyone actually maintaining this package?

**Comment by natschil** [comment]
There is an example using OceanTools.jl below the first image in https://coherentstructures.github.io/CoherentStructures.jl/latest/generated/turbulence/ 

Basically, `OceanTools.jl` is optimized towards interpolating velocity fields given on a regular (possibly periodic) space-time grid. In this setting, let `data`be the thing you want to interpolate - a variable of type `T` with `data[1]` and `data[2]` being x and y components of a time-dependent velocity field on a regular 3D grid, i.e. data[1][1,1,1] should make sense. You need to create an object of type ItpMetadata{T}  (let's call it `p`) with `p.data` being the just mentioned `data` object. Then you call `uv_tricubic(x,p,t)` (or `uv_trilinear(x,p,t)`) to evaluate the interpolation at space-time points (x,t) using Leikien-Marsden tricubic interpolation (or  trilinear interpolation).

As for the `ItpMetadata` type - there are constructors for this in case you want to interpolate velocity fields coming from NetCDF files from Copernicus. If this is not where your data is coming from:  `UR` and `LL` are the upper-right and lower-left corners of the (2+1 dimensional space-time) domain in question. The lower-left datapoint (i.e. `data[i][1,1,1]` for i=1,2) should be at `LL`. `UR` is **one grid spacing beyond** the upper right datapoint. For example, if you want to interpolate on a globe, you want something like LL = [0.0,-90.0,t0] and UR=[360,90.0,tf].  The fields `nx`, `ny` and `nt` are how many points you have in each dimension. The three fields of `BoundaryBehaviour` type ( `@enum BoundaryBehaviour periodic=0 flat=1 outofbounds=2`) say what should be done if a value is required that is out of bounds in each direction. The behaviour is as if you extended the grid to an infinite one in the way specified. Note that if you specify `outofbounds`, some values within the domain will also throw an error as for interpolation you need values at all points in the grid surrounding (or even further away for tricubic interpolation) the point in question. 

Interpolating scalars can either be done the quick and dirty way by just making a "velocity field" where both components are the scalar in question, or by using `ssh_tricubic` and putting the scalar field in data[7]. As I'm typing this I'm realizing that I need to clean up the interface as every part of that sentence is too counterintuitive.

I have some further methods I want to add to the package, and will add documentation once these work. Basically the end goal is to be able to interpolate any space-time "box" of ocean velocities on the globe. The tricky thing is that it should do the right thing if LL = [350, 0, 0,] and UR = [10,0,0] even though 350 > 10.

**Comment by natschil** [comment]
The new version of OceanTools.jl addresses these issues.

**Comment by briochemc** [comment]
@natschil Could you document how you did the periodic interpolation using your package? Maybe by providing a 1D, 2D and 3D MWEs? I just got bitten by a case where adding ghost points did not work and would love to use a cleaner implementation.

Also maybe your solution would benefit the broader Julia community if you could directly add it to Interpolations.jl, which has a new maintainer? (cc @mkitti)

**Comment by natschil** [comment]
@briochemc: I only have code in 3 (or, in one case, 4) dimensions. 

Here is a MWE:
```
using OceanTools
 xspan = range(0, stop=10.0, length=10)
 yspan = range(0, stop=10.0, length=10)
 tspan = range(0, stop=10.0, length=10)
 fu(x,y,t) = x^2 + y^2 - t

 U = [fu(x,y,t) for x in xspan, y in yspan, t in tspan]
  metadata = OceanTools.ItpMetadata(xspan, yspan, tspan,
             (U,), OceanTools.periodic, OceanTools.periodic, OceanTools.periodic)
#Now you can interpolate as much as you want
scalar_tricubic((@SVector [3.4,3.5]),metadata,1.5)
```

In principle, I have nothing against adding this to Interpolations.jl. All of the code is in principle straight-forward (though in practice, slightly less because it is quite highly optimized), except maybe the tricubic interpolation based on the paper from Lekien and Marsden. However, since this method is a "real" 3D method (not decomposable into three 1D interpolations) I'm not sure how it would fit into the general Interpolations.jl framework. I'm happy if someone wants to take my code and add it to Interpolations.jl (it is, after all, all open source), but personally I'm in the middle of writing my thesis so I don't have the time.

**Comment by natschil** [comment]
@briochemc: I only have code in 3 (or, in one case, 4) dimensions. All of the relevant code is in src/interpolations.jl, basically I just assume everything is in memory like a regular mesh with (n-1) points in each direction, and point n should be identified with point 1.  

Here is a MWE:
```
using OceanTools, StaticArrays
 xspan = range(0, stop=10.0, length=10)[1:end-1]
 yspan = range(0, stop=10.0, length=10)[1:end-1]
 tspan = range(0, stop=10.0, length=10)[1:end-1]
 fu(x,y,t) = x^2 + y^2 - t

 U = [fu(x,y,t) for x in xspan, y in yspan, t in tspan]
  metadata = OceanTools.ItpMetadata(xspan, yspan, tspan,
             (U,), OceanTools.periodic, OceanTools.periodic, OceanTools.periodic)
#Now you can interpolate as much as you want, this function is (10,10,10)-periodic 
scalar_tricubic((@SVector [3.4,3.5]),metadata,1.5)
```
 I have nothing against adding my code to Interpolations.jl. All of the code is in principle straight-forward (though in practice, slightly less because it is quite highly optimized), except maybe the tricubic interpolation based on the paper from Lekien and Marsden. However, since this method is a "real" 3D method (not decomposable into three 1D interpolations) I'm not sure how it would fit into the general Interpolations.jl framework. I'm happy if someone wants to take my code and add it to Interpolations.jl (it is, after all, all open source), but personally I'm in the middle of writing my thesis so I don't have the time.
